"""Render INDEX.md — one file that shows the whole backlog at a glance."""

from __future__ import annotations

from datetime import date
from pathlib import Path

from .loader import TaskRef
from .paths import Paths
from .schema import OPEN_STATUSES
from .workflow import pick_next


def _cell(text: str, limit: int = 80) -> str:
    """Collapse text into a single table cell, escaping the column separator."""
    text = (text or "").replace("|", "\\|").replace("\n", " ").strip()
    return text if len(text) <= limit else text[: limit - 1] + "…"


def counts(refs: list[TaskRef]) -> dict[str, int]:
    result = dict.fromkeys((*OPEN_STATUSES, "done"), 0)
    for ref in refs:
        result[ref.task.status] = result.get(ref.task.status, 0) + 1
    return result


def render_index(paths: Paths, refs: list[TaskRef], today: date | None = None) -> str:
    stats = counts(refs)
    open_refs = [ref for ref in refs if ref.task.status in OPEN_STATUSES]
    closed_refs = [ref for ref in refs if ref.task.status == "done"]

    lines = [
        f"# {paths.config.project_name} — task index",
        "",
        "_Generated by `tasc reindex`. Do not edit by hand._  "
        f"Updated: {(today or date.today()).isoformat()}",
        "",
        f"**todo:** {stats['todo']} | **in_progress:** {stats['in_progress']} | "
        f"**blocked:** {stats['blocked']} | **done:** {stats['done']}",
        "",
        "## Next to pick",
        "",
    ]

    next_refs = pick_next(refs, limit=5)
    if next_refs:
        lines += [
            f"- `{ref.task.id}` ({ref.task.priority}) — {_cell(ref.task.summary, 100)}"
            for ref in next_refs
        ]
    else:
        lines.append("- _Nothing ready: every task is done, blocked, or waiting on a dependency._")

    lines += ["", "## Open", ""]
    if open_refs:
        lines += [
            "| ID | Status | Priority | Epic | Owner | Summary | File |",
            "|----|--------|----------|------|-------|---------|------|",
        ]
        ordered = sorted(
            open_refs,
            key=lambda ref: (
                0 if ref.task.status == "in_progress" else 1,
                ref.task.priority_rank,
                ref.task.id,
            ),
        )
        lines += [
            f"| `{ref.task.id}` | {ref.task.status} | {ref.task.priority} | {ref.epic} "
            f"| {_cell(ref.task.owner or '—', 40)} | {_cell(ref.task.summary)} "
            f"| `{paths.relative(ref.file)}` |"
            for ref in ordered
        ]
    else:
        lines.append("_No open tasks._")

    lines += ["", "## Done — by epic"]
    by_epic: dict[str, list[TaskRef]] = {}
    for ref in closed_refs:
        by_epic.setdefault(ref.epic, []).append(ref)
    if not by_epic:
        lines += ["", "_Nothing closed yet._"]
    for epic, items in sorted(by_epic.items()):
        lines += ["", f"### {epic} ({len(items)})", ""]
        lines += [
            f"- `{ref.task.id}` — {_cell(ref.task.summary, 100)}"
            for ref in sorted(items, key=lambda ref: ref.task.id)
        ]

    return "\n".join(lines) + "\n"


def write_index(paths: Paths, refs: list[TaskRef]) -> Path:
    paths.index_md.parent.mkdir(parents=True, exist_ok=True)
    paths.index_md.write_text(render_index(paths, refs), encoding="utf-8")
    return paths.index_md
