"""CLI surface for parallel agents: --owner, --epic, --shard, and the ignored index."""

from __future__ import annotations

import json
from pathlib import Path

from typer.testing import CliRunner

from tasks_as_code.cli import app
from tasks_as_code.core.paths import Paths

from .conftest import make_task

runner = CliRunner()


def run(*args: str) -> tuple[int, str]:
    result = runner.invoke(app, list(args))
    return result.exit_code, " ".join(f"{result.stdout}\n{result.stderr}".split())


def payload(*args: str) -> dict:
    return json.loads(runner.invoke(app, list(args)).stdout)


def test_next_owner_hides_other_agents_work(in_project: Paths, add_epic) -> None:
    add_epic(
        "api",
        [
            make_task("api-001", priority="Critical", owner="agent-b"),
            make_task("api-002", priority="High"),
        ],
    )
    data = payload("next", "--json", "--owner", "agent-a", "--limit", "5")
    assert [task["id"] for task in data["next"]] == ["api-002"]


def test_next_owner_also_filters_the_in_progress_warning(in_project: Paths, add_epic) -> None:
    """Another agent's open task is not this agent's problem to report."""
    add_epic("api", [make_task("api-001", status="in_progress", owner="agent-b")])
    assert payload("next", "--json", "--owner", "agent-a")["in_progress"] == []
    assert len(payload("next", "--json", "--owner", "agent-b")["in_progress"]) == 1


def test_next_epic_scopes_selection(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001", priority="Critical")])
    add_epic("ui", [make_task("ui-001", priority="Low")])
    data = payload("next", "--json", "--epic", "ui", "--limit", "5")
    assert [task["id"] for task in data["next"]] == ["ui-001"]


def test_next_shards_are_disjoint(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task(f"api-{n:03d}") for n in range(30)])
    picked = [payload("next", "--json", "--shard", f"{k}/3")["next"][0]["id"] for k in (1, 2, 3)]
    assert len(set(picked)) == 3


def test_next_rejects_a_malformed_shard(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001")])
    code, out = run("next", "--shard", "4/3")
    assert code == 1
    assert "index <= total" in out
    assert "error" in payload("next", "--json", "--shard", "oops")


def test_next_hint_repeats_the_owner_so_the_claim_sticks(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001")])
    _, out = run("next", "--owner", "agent-a")
    assert "tasc mark api-001 in_progress --owner agent-a" in out


def test_mark_claims_and_refuses_to_steal(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001")])
    claimed = payload("mark", "api-001", "in_progress", "--owner", "agent-a", "--json")
    assert claimed["owner"] == "agent-a"

    code, out = run("mark", "api-001", "blocked", "--owner", "agent-b")
    assert code == 1
    assert "already owned by agent-a" in out


def test_new_can_assign_on_creation(in_project: Paths) -> None:
    assert payload("new", "api", "-s", "Ship it", "--owner", "agent-a", "--json")["owner"] == (
        "agent-a"
    )


def test_list_filters_by_owner_and_by_nobody(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001", owner="agent-a"), make_task("api-002")])
    assert [t["id"] for t in payload("list", "--json", "-o", "agent-a")["tasks"]] == ["api-001"]
    assert [t["id"] for t in payload("list", "--json", "-o", "none")["tasks"]] == ["api-002"]


def test_list_shows_the_owner_column(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001", owner="agent-a")])
    _, out = run("list")
    assert "Owner" in out
    assert "agent-a" in out


def test_show_reports_ownership(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001", owner="agent-a")])
    assert "owner: agent-a" in run("show", "api-001")[1]


def test_stale_names_the_owner_to_chase(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001", status="in_progress", owner="agent-a")])
    code, out = run("stale")
    assert code == 1
    assert "owner: agent-a" in out


def test_index_shows_owners(in_project: Paths, add_epic) -> None:
    add_epic("api", [make_task("api-001", owner="agent-a")])
    run("reindex")
    assert "agent-a" in in_project.index_md.read_text()


def test_init_gitignores_the_generated_index(tmp_path: Path, monkeypatch) -> None:
    """A file regenerated by every write must not be tracked, or every PR conflicts."""
    monkeypatch.chdir(tmp_path)
    code, out = run("init")
    assert code == 0
    assert "tasks/INDEX.md" in (tmp_path / ".gitignore").read_text()
    assert ".gitignore" in out


def test_init_appends_to_an_existing_gitignore(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    (tmp_path / ".gitignore").write_text("__pycache__/")  # no trailing newline
    run("init")

    lines = (tmp_path / ".gitignore").read_text().splitlines()
    assert "__pycache__/" in lines
    assert "tasks/INDEX.md" in lines


def test_init_does_not_duplicate_the_ignore_entry(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    run("init")
    run("init", "--force")
    assert (tmp_path / ".gitignore").read_text().count("tasks/INDEX.md") == 1


def test_init_track_index_leaves_gitignore_alone(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    run("init", "--track-index")
    assert not (tmp_path / ".gitignore").exists()


def test_init_ignore_entry_follows_a_custom_tasks_dir(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    run("init", "--tasks-dir", "work")
    assert "work/INDEX.md" in (tmp_path / ".gitignore").read_text()


def test_init_writes_a_custom_done_dir_into_the_config(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.chdir(tmp_path)
    run("init", "--done-dir", "docs/changelog")

    assert (tmp_path / "docs" / "changelog").is_dir()
    assert Paths(tmp_path).done == tmp_path / "docs" / "changelog"
