"""``tasc`` — the command line interface.

Every read command supports ``--json`` so a coding agent consumes the same
output a human reads, without scraping formatted tables.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, NoReturn

import typer
from rich.console import Console
from rich.markup import escape
from rich.panel import Panel
from rich.table import Table

from . import __version__
from .core.config import CONFIG_FILENAME, Config
from .core.indexer import counts, write_index
from .core.loader import TaskFileError, TaskRef, load_active, load_all, write_active_file
from .core.paths import Paths, ProjectNotFound
from .core.refs import check_text
from .core.schema import Task
from .core.workflow import (
    InvalidTransition,
    TaskNotFound,
    archive,
    blocking_dependencies,
    create,
    parse_shard,
    pick_next,
    record_jira_key,
    require,
    set_status,
    stale_in_progress,
)

app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help="Tasks as code: a git-native backlog for AI coding agents and humans.",
)
console = Console()
# Errors quote file paths and task ids. Rich's word wrap folds a long path across
# lines, inserting a break inside the token, which makes it uncopyable — so let
# the terminal wrap error output instead of rewriting it.
err_console = Console(stderr=True, soft_wrap=True)

STATUS_COLOURS = {
    "in_progress": "yellow",
    "todo": "white",
    "blocked": "red",
    "done": "green",
}


def _emit(payload: Any) -> None:
    """Write machine-readable output to stdout with nothing else mixed in."""
    print(json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True))


def _fail(message: str, as_json: bool = False) -> NoReturn:
    if as_json:
        print(json.dumps({"error": message}, indent=2, ensure_ascii=False))
    else:
        err_console.print(f"[red]{message}[/red]")
    raise typer.Exit(1)


def _paths(as_json: bool = False) -> Paths:
    try:
        return Paths.discover()
    except ProjectNotFound as exc:
        _fail(str(exc), as_json)


def _load(paths: Paths, as_json: bool = False, active_only: bool = False) -> list[TaskRef]:
    try:
        return load_active(paths) if active_only else load_all(paths)
    except TaskFileError as exc:
        _fail(f"Invalid task file: {exc}", as_json)


def _ensure_index_ignored(paths: Paths) -> bool:
    """Add the index to ``.gitignore``, returning whether the file was changed.

    ``INDEX.md`` is regenerated by every ``new``, ``mark`` and ``done``. Tracking
    it means two agents on separate branches conflict in almost every pull
    request, over a file that is derived from the YAML anyway. So it is generated
    locally and in CI instead of being committed.
    """
    pattern = paths.relative(paths.index_md)
    gitignore = paths.root / ".gitignore"
    existing = gitignore.read_text(encoding="utf-8") if gitignore.is_file() else ""
    if pattern in existing.split():
        return False
    prefix = "" if not existing or existing.endswith("\n") else "\n"
    note = "# Generated by 'tasc reindex' — regenerate it, do not track it.\n"
    gitignore.write_text(f"{existing}{prefix}{note}{pattern}\n", encoding="utf-8")
    return True


def _version_callback(value: bool) -> None:
    # Must run while parameters are parsed: by the time the group callback body
    # would run, Click has already rejected the missing subcommand.
    if value:
        print(__version__)
        raise typer.Exit()


@app.callback()
def _root(
    version: bool = typer.Option(
        False,
        "--version",
        "-V",
        callback=_version_callback,
        is_eager=True,
        help="Print the version and exit.",
    ),
) -> None:
    """Tasks as code: a git-native backlog for AI coding agents and humans."""


@app.command("init")
def cmd_init(
    directory: Path | None = typer.Option(
        None, "--dir", "-d", help="Repository root to initialise. Defaults to the cwd."
    ),
    name: str = typer.Option("Project", "--name", "-n", help="Project name for the index."),
    tasks_dir: str = typer.Option("tasks", "--tasks-dir", help="Directory to hold tasks."),
    done_dir: str | None = typer.Option(
        None, "--done-dir", help="Where quarterly logs live. Defaults to <tasks-dir>/done."
    ),
    track_index: bool = typer.Option(
        False, "--track-index", help="Commit INDEX.md instead of git-ignoring it."
    ),
    force: bool = typer.Option(False, "--force", help="Overwrite an existing config file."),
) -> None:
    """Create the task tree and config file. Existing files are left alone."""
    root = (directory or Path.cwd()).resolve()
    config_path = root / CONFIG_FILENAME
    if config_path.exists() and not force:
        _fail(f"{config_path} already exists. Pass --force to overwrite it.")

    config = Config(project_name=name, tasks_dir=tasks_dir, done_dir=done_dir)
    paths = Paths(root, config)
    for folder in (paths.active, paths.archive, paths.done):
        folder.mkdir(parents=True, exist_ok=True)
    config.dump(config_path)

    example = paths.active / "core.yaml"
    if not example.exists():
        write_active_file(
            example,
            epic="core",
            description="Example epic. Rename it or delete it.",
            tasks=[
                Task(
                    id="core-001",
                    summary="Replace this example task with real work",
                    description="Created by 'tasc init' to show the file format.",
                    priority="Medium",
                )
            ],
        )
    write_index(paths, _load(paths))

    console.print(
        f"[green]Initialised[/green] {paths.relative(paths.tasks)}/ and {CONFIG_FILENAME}"
    )
    if not track_index and _ensure_index_ignored(paths):
        console.print(f"Added {paths.relative(paths.index_md)} to .gitignore")
    console.print("Next: [bold]tasc next[/bold]")


@app.command("next")
def cmd_next(
    limit: int = typer.Option(1, "--limit", "-n", help="How many tasks to suggest."),
    owner: str | None = typer.Option(
        None,
        "--owner",
        "-o",
        envvar="TASC_OWNER",
        help="Only unowned tasks and your own. Also filters in-progress.",
    ),
    epic: str | None = typer.Option(
        None, "--epic", "-e", envvar="TASC_EPIC", help="Only tasks from this epic."
    ),
    shard: str | None = typer.Option(
        None,
        "--shard",
        envvar="TASC_SHARD",
        help="Take a disjoint slice of the backlog, e.g. '2/3'.",
    ),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Show the next ready task(s), highest priority first.

    In-progress work is reported first: picking up something new while a task is
    already open is the most common way an agent loses track of what it started.

    Selection is deterministic, so parallel agents asking at the same moment all
    receive the same task. Use ``--owner``, ``--epic`` or ``--shard`` to give each
    agent its own slice; ``--shard`` needs no coordination between them.

    All three read TASC_OWNER, TASC_EPIC and TASC_SHARD, so a person or an agent
    sets its lane once in the environment instead of on every invocation. Active
    filters are named in the output. ``tasc list`` deliberately ignores them, so
    there is always one command that shows the whole backlog.
    """
    paths = _paths(as_json)
    refs = _load(paths, as_json)
    try:
        parsed_shard = parse_shard(shard) if shard else None
    except ValueError as exc:
        _fail(str(exc), as_json)

    in_progress = [ref for ref in refs if ref.task.status == "in_progress"]
    if owner:
        in_progress = [ref for ref in in_progress if ref.task.owner in (None, owner)]
    ready = pick_next(refs, limit=limit, owner=owner, epic=epic, shard=parsed_shard)

    if as_json:
        _emit(
            {
                "in_progress": [ref.to_dict(paths) for ref in in_progress],
                "next": [ref.to_dict(paths) for ref in ready],
            }
        )
        return

    # Filters can come from TASC_EPIC, TASC_OWNER or TASC_SHARD in the shell
    # profile. Say which are active, so an exported variable someone set weeks ago
    # cannot quietly hide the backlog and look like an empty one.
    active = [
        f"{label}={value}"
        for label, value in (("epic", epic), ("owner", owner), ("shard", shard))
        if value
    ]
    if active:
        console.print(f"[dim]Filtered by {', '.join(active)}[/dim]\n")

    if in_progress:
        console.print("[yellow]Already in progress:[/yellow]")
        for ref in in_progress:
            who = f" [{ref.task.owner}]" if ref.task.owner else ""
            console.print(f"  [bold]{ref.task.id}[/bold]{who} — {ref.task.summary}")
        console.print("")

    if not ready:
        console.print(
            "[green]Nothing ready — all done, blocked, or waiting on dependencies.[/green]"
        )
        return

    for ref in ready:
        body = [
            f"[bold]{ref.task.id}[/bold] — {ref.task.summary}",
            f"epic: {ref.epic}   priority: {ref.task.priority}   file: {paths.relative(ref.file)}",
        ]
        if ref.task.description:
            body += ["", ref.task.description]
        if ref.task.acceptance_criteria:
            body += ["", "[bold]Acceptance criteria:[/bold]"]
            body += [f"  - {item}" for item in ref.task.acceptance_criteria]
        console.print(Panel("\n".join(body), border_style="green"))

    claim = f" --owner {owner}" if owner else ""
    console.print(f"\nStart it: [bold]tasc mark {ready[0].task.id} in_progress{claim}[/bold]")


@app.command("show")
def cmd_show(
    task_id: str,
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Show one task in full, including what is blocking it."""
    paths = _paths(as_json)
    refs = _load(paths, as_json)
    try:
        ref = require(refs, task_id)
    except TaskNotFound as exc:
        _fail(str(exc), as_json)

    blocking = blocking_dependencies(ref, refs)
    if as_json:
        _emit({**ref.to_dict(paths), "blocking_dependencies": blocking})
        return

    task = ref.task
    console.print(f"[bold]{task.id}[/bold] — {task.summary}")
    console.print(f"epic:      {ref.epic}")
    console.print(f"status:    {task.status}")
    console.print(f"priority:  {task.priority}")
    console.print(f"type:      {task.type}")
    console.print(f"owner:     {task.owner or '—'}")
    console.print(f"updated:   {task.updated or '—'}")
    console.print(f"file:      {paths.relative(ref.file)}")
    if task.depends_on:
        console.print(f"depends:   {', '.join(task.depends_on)}")
    if blocking:
        console.print(f"[red]blocked by: {', '.join(blocking)}[/red]")
    if task.description:
        console.print(f"\n{task.description}")
    if task.acceptance_criteria:
        console.print("\n[bold]Acceptance criteria:[/bold]")
        for item in task.acceptance_criteria:
            console.print(f"  - {item}")


@app.command("list")
def cmd_list(
    epic: str | None = typer.Option(None, "--epic", "-e", help="Filter by epic."),
    status: str | None = typer.Option(None, "--status", "-s", help="Filter by status."),
    owner: str | None = typer.Option(
        None, "--owner", "-o", help="Filter by owner. Use 'none' for unassigned tasks."
    ),
    include_done: bool = typer.Option(False, "--all", help="Include archived tasks."),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """List tasks. Active only by default."""
    paths = _paths(as_json)
    refs = _load(paths, as_json, active_only=not include_done)

    if epic:
        refs = [ref for ref in refs if ref.epic == epic or ref.task.epic_prefix == epic]
    if status:
        refs = [ref for ref in refs if ref.task.status == status]
    if owner:
        wanted = None if owner.lower() == "none" else owner
        refs = [ref for ref in refs if ref.task.owner == wanted]

    refs.sort(
        key=lambda ref: (
            0 if ref.task.status == "in_progress" else 1,
            ref.task.priority_rank,
            ref.task.id,
        )
    )

    if as_json:
        _emit({"count": len(refs), "tasks": [ref.to_dict(paths) for ref in refs]})
        return

    table = Table(show_header=True, header_style="bold")
    for column in ("ID", "Status", "Priority", "Epic", "Owner", "Summary"):
        table.add_column(column)
    for ref in refs:
        colour = STATUS_COLOURS.get(ref.task.status, "white")
        table.add_row(
            ref.task.id,
            f"[{colour}]{ref.task.status}[/{colour}]",
            ref.task.priority,
            ref.epic,
            ref.task.owner or "—",
            ref.task.summary[:80],
        )
    console.print(table)
    console.print(f"\nTotal: {len(refs)}")


@app.command("new")
def cmd_new(
    epic: str = typer.Argument(..., help="Epic prefix, e.g. 'api' or 'ui'."),
    summary: str = typer.Option(..., "--summary", "-s", help="One-line summary."),
    priority: str = typer.Option("Medium", "--priority", "-p", help="Critical|High|Medium|Low."),
    description: str = typer.Option("", "--description", "-d", help="Longer description."),
    owner: str | None = typer.Option(None, "--owner", "-o", help="Assign the task on creation."),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Create a task with an auto-numbered id."""
    paths = _paths(as_json)
    try:
        ref = create(
            paths,
            epic_prefix=epic,
            summary=summary,
            priority=priority,
            description=description,
            owner=owner,
        )
    except Exception as exc:
        _fail(f"Could not create task: {exc}", as_json)
    write_index(paths, _load(paths, as_json))

    if as_json:
        _emit(ref.to_dict(paths))
        return
    console.print(
        f"[green]Created[/green] [bold]{ref.task.id}[/bold] in {paths.relative(ref.file)}"
    )


@app.command("mark")
def cmd_mark(
    task_id: str,
    status: str = typer.Argument(..., help="todo | in_progress | blocked"),
    owner: str | None = typer.Option(
        None,
        "--owner",
        "-o",
        envvar="TASC_OWNER",
        help="Claim the task for this owner in the same write.",
    ),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Change a task's status and stamp today's date.

    Pass ``--owner`` to claim it at the same time; claiming a task somebody else
    already owns fails instead of quietly stealing it.
    """
    paths = _paths(as_json)
    try:
        ref = set_status(paths, task_id, status, owner=owner)
    except (TaskNotFound, InvalidTransition) as exc:
        _fail(str(exc), as_json)
    write_index(paths, _load(paths, as_json))

    if as_json:
        _emit(ref.to_dict(paths))
        return
    claimed = f" as [bold]{ref.task.owner}[/bold]" if ref.task.owner else ""
    console.print(
        f"[green]{task_id}[/green] -> [bold]{status}[/bold]{claimed} ({ref.task.summary})"
    )


@app.command("done")
def cmd_done(
    task_id: str,
    note: str | None = typer.Option(None, "--note", "-m", help="What was actually done."),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Close a task: mark done, move to archive, append to the quarterly log."""
    paths = _paths(as_json)
    if paths.config.require_note and not (note or "").strip():
        _fail(
            f'Closing {task_id} needs its outcome: tasc done {task_id} --note "what came '
            'out of it". Set require_note: false in .tasc.yaml to close without one.',
            as_json,
        )
    try:
        archive_path, log_path = archive(paths, task_id, note=note)
    except (TaskNotFound, InvalidTransition) as exc:
        _fail(str(exc), as_json)
    write_index(paths, _load(paths, as_json))

    if as_json:
        _emit(
            {
                "id": task_id,
                "archived_to": paths.relative(archive_path),
                "logged_in": paths.relative(log_path),
            }
        )
        return
    console.print(f"[green]{task_id}[/green] archived -> {paths.relative(archive_path)}")
    console.print(f"Logged in {paths.relative(log_path)}")


@app.command("reindex")
def cmd_reindex(
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Regenerate INDEX.md from the current YAML state."""
    paths = _paths(as_json)
    refs = _load(paths, as_json)
    index_path = write_index(paths, refs)
    if as_json:
        _emit({"index": paths.relative(index_path), "tasks": len(refs), **counts(refs)})
        return
    console.print(f"[green]Wrote[/green] {paths.relative(index_path)} ({len(refs)} tasks)")


@app.command("validate")
def cmd_validate(
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Check every file against the schema and report structural problems.

    Exits non-zero on any problem, so it works as a pre-commit hook or CI gate.
    """
    paths = _paths(as_json)
    try:
        refs = load_all(paths)
    except TaskFileError as exc:
        _fail(f"Invalid task file: {exc}", as_json)

    problems: list[str] = []

    seen: dict[str, int] = {}
    for ref in refs:
        seen[ref.task.id] = seen.get(ref.task.id, 0) + 1
    problems += [f"duplicate id: {task_id}" for task_id, n in sorted(seen.items()) if n > 1]

    known = set(seen)
    for ref in refs:
        problems += [
            f"{ref.task.id} depends on unknown task: {dep}"
            for dep in ref.task.depends_on
            if dep not in known
        ]
        if ref.task.id in ref.task.depends_on:
            problems.append(f"{ref.task.id} depends on itself")

    if as_json:
        _emit({"ok": not problems, "tasks": len(refs), "problems": problems})
        raise typer.Exit(1 if problems else 0)

    if problems:
        err_console.print(f"[red]{len(problems)} problem(s):[/red]")
        for problem in problems:
            err_console.print(f"  - {problem}")
        raise typer.Exit(1)
    console.print(f"[green]OK[/green] — {len(refs)} tasks valid")


#: Delegates rather than reimplements the rule, so upgrading tasc upgrades the
#: hook. Missing tasc is a warning, not a failure: a teammate without the tool
#: installed should not be unable to commit.
_COMMIT_MSG_HOOK = """#!/bin/sh
# Installed by 'tasc install-hook'. Remove this file to stop the check.
if command -v tasc >/dev/null 2>&1; then
    exec tasc check-ref --file "$1"
fi
echo "tasc not found; skipping the task reference check." >&2
"""

#: Runs before the editor opens, so the author sees the stamped subject and can
#: still change it. Merges and squashes are left alone: their messages are git's,
#: and the check exempts them anyway.
_PREPARE_COMMIT_MSG_HOOK = """#!/bin/sh
# Installed by 'tasc install-hook'. Remove this file to stop filling in issue keys.
case "$2" in
    merge|squash) exit 0 ;;
esac
if command -v tasc >/dev/null 2>&1; then
    exec tasc stamp "$1"
fi
"""


def _git_hooks_dir(root: Path) -> Path | None:
    """Locate the hooks directory, following the gitfile a worktree leaves behind."""
    git = root / ".git"
    if git.is_dir():
        return git / "hooks"
    if git.is_file():
        # Worktrees and submodules store "gitdir: <path>" instead of a directory.
        for line in git.read_text(encoding="utf-8").splitlines():
            if line.startswith("gitdir:"):
                target = Path(line.partition(":")[2].strip())
                resolved = target if target.is_absolute() else (root / target).resolve()
                return resolved / "hooks"
    return None


@app.command("install-hook")
def cmd_install_hook(
    force: bool = typer.Option(False, "--force", help="Overwrite existing hooks of these types."),
) -> None:
    """Install the commit-msg and prepare-commit-msg hooks.

    For repositories not using pre-commit. Git hooks are per-clone and cannot be
    committed, so this is what each person runs once; CI is what actually
    enforces the rule for everyone.
    """
    paths = _paths()
    hooks = _git_hooks_dir(paths.root)
    if hooks is None:
        _fail(f"No git repository found at {paths.root}")

    wanted = {"commit-msg": _COMMIT_MSG_HOOK, "prepare-commit-msg": _PREPARE_COMMIT_MSG_HOOK}
    present = [name for name in wanted if (hooks / name).exists()]
    if present and not force:
        _fail(f"{', '.join(present)} already exist(s) in {hooks}. Pass --force to replace.")

    hooks.mkdir(parents=True, exist_ok=True)
    for name, body in wanted.items():
        hook = hooks / name
        hook.write_text(body, encoding="utf-8")
        # On POSIX this is what makes git run the file rather than ignore it.
        # Windows has no execute bit, so the call only clears the read-only flag.
        hook.chmod(0o755)
        console.print(f"[green]Installed[/green] {hook}")
    console.print(
        "Commits must now name a task, and carry its issue key where it has one. "
        "Bypass a single commit with --no-verify."
    )


@app.command("stamp")
def cmd_stamp(
    file: Path = typer.Argument(
        ..., help="File holding the message, as prepare-commit-msg hooks pass it."
    ),
) -> None:
    """Write the task's issue key into a commit message.

    Meant as a prepare-commit-msg hook: the author writes the message they would
    write anyway, and the key that links the commit to its issue is filled in from
    the backlog. Always exits zero — a message that could not be stamped is for
    ``check-ref`` to accept or refuse, and failing here would only block the commit
    before the author sees why.
    """
    from .core.messages import stamp_message

    try:
        text = file.read_text(encoding="utf-8")
    except OSError as exc:
        err_console.print(f"[yellow]Could not read {file}: {exc}[/yellow]")
        return

    paths = _paths()
    result = stamp_message(
        text,
        _load(paths),
        subject_format=paths.config.refs.subject_format,
        skip_markers=paths.config.refs.skip_markers,
    )
    if result.changed:
        file.write_text(result.text, encoding="utf-8")
        console.print(f"[green]Stamped[/green] {result.key} onto the message")
        return
    if result.reason:
        console.print(f"[yellow]Left as written[/yellow] — {escape(result.reason)}")


@app.command("check-ref")
def cmd_check_ref(
    text: str | None = typer.Argument(None, help="Text to check. Omit to read stdin."),
    file: Path | None = typer.Option(
        None, "--file", "-f", help="Read the text from a file, as commit-msg hooks pass it."
    ),
    require_status: list[str] = typer.Option(
        [], "--require-status", help="Demand one of these statuses. Repeatable."
    ),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Check that a commit message, PR title or branch name names a real task.

    A regex in a hook can already demand that some id is present. This checks the
    id against the backlog, which is the part that catches an agent citing a task
    it invented. Exits non-zero on failure, so it works as a commit-msg hook and
    as a required status check.
    """
    if file is not None:
        try:
            text = file.read_text(encoding="utf-8")
        except OSError as exc:
            _fail(f"Could not read {file}: {exc}", as_json)
    elif text is None:
        text = sys.stdin.read()

    paths = _paths(as_json)
    refs = _load(paths, as_json)
    settings = paths.config.refs
    result = check_text(
        text,
        refs,
        skip_markers=settings.skip_markers,
        require_status=require_status or settings.require_status,
    )

    if as_json:
        _emit(result.to_dict())
        raise typer.Exit(0 if result.ok else 1)

    if result.skipped:
        # Markers are bracketed by convention, which is also Rich's markup syntax:
        # printed unescaped, "[skip-task]" renders as nothing at all.
        console.print(f"[yellow]Skipped[/yellow] — {escape(result.skipped)}")
        return
    if result.ok:
        console.print(f"[green]OK[/green] — references {', '.join(result.referenced)}")
        return

    err_console.print("[red]No valid task reference:[/red]")
    for problem in result.problems():
        err_console.print(f"  - {escape(problem)}")
    marker = settings.skip_markers[0] if settings.skip_markers else "[skip-task]"
    err_console.print(
        f"\nRun [bold]tasc next[/bold] to see what to work on, or add {escape(marker)} to bypass."
    )
    raise typer.Exit(1)


@app.command("stale")
def cmd_stale(
    days: int | None = typer.Option(None, "--days", help="Override the configured threshold."),
    as_json: bool = typer.Option(False, "--json", help="Machine-readable output."),
) -> None:
    """Report tasks stuck in progress, including any with no ``updated`` date.

    Exits non-zero when something is stale, so CI can catch abandoned work.
    """
    paths = _paths(as_json)
    refs = _load(paths, as_json)
    threshold = days if days is not None else paths.config.stale_after_days
    stale = stale_in_progress(refs, days=threshold)

    if as_json:
        _emit(
            {
                "threshold_days": threshold,
                "count": len(stale),
                "stale": [ref.to_dict(paths) for ref in stale],
            }
        )
        raise typer.Exit(1 if stale else 0)

    if not stale:
        console.print(f"[green]OK[/green] — nothing in progress longer than {threshold} days")
        return
    err_console.print(f"[yellow]{len(stale)} stale task(s) (threshold {threshold} days):[/yellow]")
    for ref in stale:
        who = f", owner: {ref.task.owner}" if ref.task.owner else ""
        err_console.print(
            f"  - {ref.task.id} (updated: {ref.task.updated or 'never'}{who}) — {ref.task.summary}"
        )
    raise typer.Exit(1)


@app.command("sync")
def cmd_sync(
    dry_run: bool = typer.Option(False, "--dry-run", help="Show what would change, send nothing."),
    check: bool = typer.Option(
        False, "--check", help="Compare the backlog against the project, then stop."
    ),
    active_only: bool = typer.Option(
        True,
        "--active-only/--all",
        help="Create issues for active tasks only. Archived tasks are still updated "
        "where an issue exists; --all creates issues for them too.",
    ),
) -> None:
    """Push tasks to Jira Cloud. Local YAML stays the source of truth."""
    from .integrations.jira import (
        JiraClient,
        JiraCredentials,
        JiraNotConfigured,
        ensure_epics,
        epic_label,
        preflight,
        sync_task,
        task_label,
    )

    paths = _paths()
    settings = paths.config.jira
    refs = _load(paths, active_only=False)
    if not refs:
        console.print("[yellow]No tasks to sync.[/yellow]")
        return

    try:
        credentials = JiraCredentials.from_env()
        client = JiraClient(credentials)
    except JiraNotConfigured as exc:
        _fail(str(exc))

    if check:
        candidates = [ref for ref in refs if ref.location == "active"] if active_only else refs
        console.print(
            f"Checking {len(candidates)} task(s) against {credentials.project_key} "
            f"on {credentials.base_url}"
        )
        findings = preflight(client, settings, candidates)
        if not findings:
            console.print("[green]OK[/green] — types, priorities, statuses and fields all line up")
            return
        for finding in findings:
            label = "[red]blocker[/red]" if finding.blocking else "[yellow]note[/yellow]"
            console.print(f"{label} {finding.message}")
        if any(finding.blocking for finding in findings):
            raise typer.Exit(1)
        return

    # One search for the whole backlog rather than one per task. A failure here is
    # not fatal: sync_task falls back to searching per task when handed no map.
    known: dict[str, dict] | None
    labels = [task_label(settings, ref.task.id) for ref in refs]
    if settings.epic_as_parent:
        labels += sorted({epic_label(settings, ref.epic) for ref in refs})
    try:
        known = client.issues_by_labels(labels)
    except Exception as exc:
        err_console.print(f"[yellow]Batched lookup failed ({exc}); searching per task.[/yellow]")
        known = None

    if active_only:
        # A closed task whose issue exists is still synced: its issue would
        # otherwise sit in the old status forever, saying work is in progress that
        # finished weeks ago. Without the map, telling which archived tasks have
        # an issue would cost a search each, so they wait for the next run.
        if known is None:
            err_console.print("[yellow]Archived tasks are skipped without the map.[/yellow]")
            refs = [ref for ref in refs if ref.location == "active"]
        else:
            refs = [
                ref
                for ref in refs
                if ref.location == "active" or task_label(settings, ref.task.id) in known
            ]

    console.print(f"Syncing {len(refs)} task(s) to {credentials.base_url}")
    if dry_run:
        console.print("[yellow]Dry run — nothing is sent.[/yellow]")

    # Before the tasks, so that two tasks of one epic cannot each create it. A
    # failure here costs the parents, not the sync.
    try:
        epics = ensure_epics(client, settings, refs, known=known, dry_run=dry_run)
    except Exception as exc:
        err_console.print(f"[yellow]Epics unavailable ({exc}); syncing without parents.[/yellow]")
        epics = {}

    table = Table(show_header=True, header_style="bold")
    table.add_column("ID")
    table.add_column("Result")
    failures = 0
    recorded = 0
    for ref in refs:
        try:
            outcome = sync_task(
                client,
                settings,
                ref,
                dry_run=dry_run,
                known=known,
                create=not active_only or ref.location == "active",
                parent=epics.get(ref.epic),
            )
            table.add_row(ref.task.id, outcome)
        except Exception as exc:
            failures += 1
            table.add_row(ref.task.id, f"[red]{exc}[/red]")
            continue
        key = getattr(outcome, "key", None)
        if key and not dry_run and record_jira_key(paths, ref.task.id, key):
            recorded += 1
    console.print(table)
    if recorded:
        console.print(f"Wrote {recorded} issue key(s) into task files — commit them.")
    if failures:
        err_console.print(f"[red]{failures} task(s) failed to sync.[/red]")
        raise typer.Exit(1)


if __name__ == "__main__":  # pragma: no cover - exercised via the console script
    sys.exit(app())
